### ISSUE TITLE
[crash] ExecutorCallAdapterFactory.java:71

### ISSUE THREAD

**Issue by hpsaturn** [kike-canaries/canairio_android#59]
**Description**
Possible crash when third party API fails

**To Reproduce**
1. Open the app only.

**Additional context**
```java
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'java.lang.String hpsaturn.pollutionreporter.api.AqicnDataResponse.status' on a null object reference
       at hpsaturn.pollutionreporter.MainActivity$1.onResponse(MainActivity.java:105)
       at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:71)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:201)
       at android.app.ActivityThread.main(ActivityThread.java:6810)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

**Comment by hpsaturn** [comment]
in the last PR it was tested and all ok
